### ISSUE TITLE
Some alerts showing as 'Ancient Retribution'

### ISSUE THREAD

**Issue by crunchyintheory** [Warframe-Community-Developers/warframe-worldstate-parser#50]
There does not appear to be a pattern to this. Other alerts with different mission types have showed as Ancient Retribution. It happens both with Genesis and my other bots that use this module.

![image](https://cloud.githubusercontent.com/assets/5205015/24262645/b6808a0a-0fc8-11e7-9f01-7cb07be5d91c.png)

![image](https://cloud.githubusercontent.com/assets/5205015/24262669/c970f7a8-0fc8-11e7-9ef0-e5a1e71785c5.png)

**Comment by aliasfalse** [comment]
this'd be from the SolNode entry for the node not being up to date, so part of warframe-worldstate-data

**Comment by aliasfalse** [comment]
Updated it [here](https://github.com/Warframe-Community-Developers/warframe-worldstate-data/commit/6c2934f8a4c64390986201771a82fac29fcf8d43).
---
Closing
